### ISSUE TITLE
Remove numpy dependency

### ISSUE THREAD

**Issue by martinal** [martinal/nbdime#4]
I used numpy some places in sequence diff algorithms mainly for the convenient slicing features, but this is not strictly necessary. Is this ok or should it be rewritten?

**Comment by minrk** [comment]
Should probably not rely on numpy. What slicing did you need it for?

**Comment by martinal** [comment]
That's what I thought.

In the brute force lcs it's used for storing 2d arrays. This code shouldn't be used in the end product.

In the (buggy and non-functional) Myers implementation it's used to slice sequences for recursive diff of left and right parts without copying. This can be handled by passing around some offsets instead. This code needs some serious reworking anyway.

**Comment by martinal** [comment]
Done.
